[package]
name = "lettuce-magician/stir"
description = "A module full of fusion utilities."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["docs","build",".moonwave","Packages","Stir.svg",".gitignore","pack.project.json","moonwave.toml","selene.toml", "Pack.rbxm"]
license = "MIT"

[dependencies]
Fusion = "elttob/fusion@0.2.0"